name: 'Install cifuzz'
description: 'Installs cifuzz given a valid download token'
inputs:
  version:
    required: true
    type: string
  cifuzz-download-token:
    required: true
    type: string
  installer-url:
    default: "http://downloads.code-intelligence.com/assets/install-cifuzz.sh" 
    type: string
runs:
  using: "composite"
  steps:
    - name: install cifuzz
      run: sh -c "$(curl -fsSL ${{ inputs.installer-url }})" ${{ inputs.download-token }} ${{ inputs.version }}
      shell: bash
