name: fuzz_with_cifuzz
on: [push]
jobs:
  fuzz:
    runs-on: ubuntu-latest
    env: 
      CIFUZZ_DOWNLOAD_TOKEN: ${{ secrets.CIFUZZ_DOWNLOAD_TOKEN }}
    steps:
      - name: install llvm
        run: |
          sudo apt update
          sudo apt install cmake clang llvm lcov
      - name: install missing library on ubuntu 24.04
        run: sudo apt install libclang-rt-dev || true
      - name: checkout
        uses: "actions/checkout@v4"
      - name: install cifuzz
        run: sh -c "$(curl -fsSL http://downloads.code-intelligence.com/assets/install-cifuzz.sh)" $CIFUZZ_DOWNLOAD_TOKEN 3.12.0
      - name: fuzz project
        continue-on-error: true
        run: cifuzz run -v --interactive=false --max-fuzzing-duration 15s
      - name: generate sarif report
        run: cifuzz findings --format=json --output=results.sarif
      - name: print sarif report
        run: cat results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
      - name: commit findings
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'zgtm@users.noreply.github.com'
          git add .cifuzz-findings
          git commit -m "Automated check-in of cifuzz findings"
          git push
