name: fuzz_with_cifuzz
on: [push]
jobs:
  fuzz:
    runs-on: ubuntu-latest
    env: 
      CIFUZZ_DOWNLOAD_TOKEN: ${{ secrets.CIFUZZ_DOWNLOAD_TOKEN }}
    steps:
      - name: install llvm
        run: |
          sudo apt update
          sudo apt install llvm-16 llvm-16-dev llvm-16-linker-tools llvm-16-runtimellvm-16-tools
      - name: checkout
        uses: "actions/checkout@v4"
      - run: sh -c "$(curl -fsSL http://downloads.code-intelligence.com/assets/install-cifuzz.sh)" $CIFUZZ_DOWNLOAD_TOKEN 3.12.0
      - run: cifuzz run --max-fuzzing-duration 15s
      - run: cifuzz findings --format=json --output=results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
      - name: commit findings
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'zgtm@users.noreply.github.com'
          git add .cifuzz-findings
          git commit -m "Automated check-in of cifuzz findings"
          git push
