name: fuzz_with_cifuzz
on: [push]
jobs:
  fuzz:
    runs-on: ubuntu-latest
  
    env:   
      CIFUZZ_DOWNLOAD_TOKEN: ${{ secrets.CIFUZZ_DOWNLOAD_TOKEN }}
      
    permissions:
      # Required to Upload findings to Github code scanning (SARIF report)
      security-events: write
      
      # Required to commit findings to repository
      contents: write
      
    steps:
    
      - name: Install llvm & lcov
        run: |
          sudo apt update
          sudo apt install cmake clang llvm lcov
          
      - name: Install missing library on ubuntu 24.04
        run: sudo apt install libclang-rt-dev || true
        
      - name: Install cifuzz
        uses: "zgtm/cifuzztest/install-cifuzz@v1.1"
        with:
          version: 3.12.0
        
      - name: Checkout repository
        uses: "actions/checkout@v4"
        
      - name: Run fuzzing
        continue-on-error: true
        run: cifuzz run -v --interactive=false --max-fuzzing-duration 15s
        
      - name: Generate findings report
        run: cifuzz findings --format=sarif --output=results.sarif
        
      - name: Upload findings to Github code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          
      - name: Commit findings and corpus to repository
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'zgtm@users.noreply.github.com'
          git add .cifuzz-findings
          git add .cifuzz-corpus
          git commit -m "Automated check-in of cifuzz findings"
          git push
