name: fuzz_with_cifuzz
on: [push]
jobs:
  download-cifuzz:
    runs-on: ubuntu-latest
    steps:
      - run: sh -c "$(curl -fsSL http://downloads.code-intelligence.com/assets/install-cifuzz.sh)" $CIFUZZ_DOWNLOAD_TOKEN 3.12.0
  run-cifuzz:
    runs-on: ubuntu-latest
    steps:
      - run: cifuzz run
