name: fuzz_with_cifuzz
on: [push]
jobs:
  checkout: 
    uses: actions/checkout@v4
  download-cifuzz:
    runs-on: ubuntu-latest
    env: 
      CIFUZZ_DOWNLOAD_TOKEN: ${{ secrets.CIFUZZ_DOWNLOAD_TOKEN }}
    steps:
      - run: ls -l 
      - run: sh -c "$(curl -fsSL http://downloads.code-intelligence.com/assets/install-cifuzz.sh)" $CIFUZZ_DOWNLOAD_TOKEN 3.12.0
      - run: ls -l ~/.local/share
  run-cifuzz:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l 
      - run: ls -l ~/.local/share
      - run: cifuzz run
      
