name: fuzz_with_cifuzz
on: [push]
jobs:
  download-cifuzz:
    runs-on: ubuntu-latest
    env: 
      CIFUZZ_DOWNLOAD_TOKEN: ${{ secrets.CIFUZZ_DOWNLOAD_TOKEN }}
    steps:
      - name: checkout
        uses: "actions/checkout@v4"
      - run: ls -l 
      - run: sh -c "$(curl -fsSL http://downloads.code-intelligence.com/assets/install-cifuzz.sh)" $CIFUZZ_DOWNLOAD_TOKEN 3.12.0
      - run: ls -l ~/.local/share
      
  run-cifuzz:
    runs-on: ubuntu-latest
    needs: download-cifuzz
    steps:
      - run: ls -l 
      - run: ls -l ~/.local/share
      - run: cifuzz run
      
